// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	article "blog/internal/handler/article"
	base "blog/internal/handler/base"
	category "blog/internal/handler/category"
	"blog/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/init/database",
				Handler: base.InitDatabaseHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Authority},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/article/create",
					Handler: article.CreateArticleHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/article/update",
					Handler: article.UpdateArticleHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/article/delete",
					Handler: article.DeleteArticleHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/article/list",
					Handler: article.GetArticleListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/article",
					Handler: article.GetArticleByIdHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Authority},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/category/create",
					Handler: category.CreateCategoryHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/category/update",
					Handler: category.UpdateCategoryHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/category/delete",
					Handler: category.DeleteCategoryHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/category/list",
					Handler: category.GetCategoryListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/category",
					Handler: category.GetCategoryByIdHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
