// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// BlogArticleColumns holds the columns for the "blog_article" table.
	BlogArticleColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime, Comment: "Create Time | 创建日期"},
		{Name: "updated_at", Type: field.TypeTime, Comment: "Update Time | 修改日期"},
		{Name: "title", Type: field.TypeString, Comment: "文章标题"},
		{Name: "content", Type: field.TypeString, Comment: "文章内容"},
		{Name: "keyword", Type: field.TypeString, Nullable: true, Comment: "关键字"},
		{Name: "visit", Type: field.TypeInt, Comment: "浏览量", Default: 0},
	}
	// BlogArticleTable holds the schema information for the "blog_article" table.
	BlogArticleTable = &schema.Table{
		Name:       "blog_article",
		Columns:    BlogArticleColumns,
		PrimaryKey: []*schema.Column{BlogArticleColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		BlogArticleTable,
	}
)

func init() {
	BlogArticleTable.Annotation = &entsql.Annotation{
		Table: "blog_article",
	}
}
