// Code generated by ent, DO NOT EDIT.

package ent

import "time"

// set field if value's pointer is not nil.
func (a *ArticleUpdate) SetNotNilUpdatedAt(value *time.Time) *ArticleUpdate {
	if value != nil {
		return a.SetUpdatedAt(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *ArticleUpdateOne) SetNotNilUpdatedAt(value *time.Time) *ArticleUpdateOne {
	if value != nil {
		return a.SetUpdatedAt(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *ArticleCreate) SetNotNilUpdatedAt(value *time.Time) *ArticleCreate {
	if value != nil {
		return a.SetUpdatedAt(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *ArticleUpdate) SetNotNilTitle(value *string) *ArticleUpdate {
	if value != nil {
		return a.SetTitle(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *ArticleUpdateOne) SetNotNilTitle(value *string) *ArticleUpdateOne {
	if value != nil {
		return a.SetTitle(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *ArticleCreate) SetNotNilTitle(value *string) *ArticleCreate {
	if value != nil {
		return a.SetTitle(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *ArticleUpdate) SetNotNilContent(value *string) *ArticleUpdate {
	if value != nil {
		return a.SetContent(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *ArticleUpdateOne) SetNotNilContent(value *string) *ArticleUpdateOne {
	if value != nil {
		return a.SetContent(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *ArticleCreate) SetNotNilContent(value *string) *ArticleCreate {
	if value != nil {
		return a.SetContent(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *ArticleUpdate) SetNotNilKeyword(value *string) *ArticleUpdate {
	if value != nil {
		return a.SetKeyword(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *ArticleUpdateOne) SetNotNilKeyword(value *string) *ArticleUpdateOne {
	if value != nil {
		return a.SetKeyword(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *ArticleCreate) SetNotNilKeyword(value *string) *ArticleCreate {
	if value != nil {
		return a.SetKeyword(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *ArticleUpdate) SetNotNilVisit(value *int) *ArticleUpdate {
	if value != nil {
		return a.SetVisit(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *ArticleUpdateOne) SetNotNilVisit(value *int) *ArticleUpdateOne {
	if value != nil {
		return a.SetVisit(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (a *ArticleCreate) SetNotNilVisit(value *int) *ArticleCreate {
	if value != nil {
		return a.SetVisit(*value)
	}
	return a
}

// set field if value's pointer is not nil.
func (c *CategoryUpdate) SetNotNilUpdatedAt(value *time.Time) *CategoryUpdate {
	if value != nil {
		return c.SetUpdatedAt(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CategoryUpdateOne) SetNotNilUpdatedAt(value *time.Time) *CategoryUpdateOne {
	if value != nil {
		return c.SetUpdatedAt(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CategoryCreate) SetNotNilUpdatedAt(value *time.Time) *CategoryCreate {
	if value != nil {
		return c.SetUpdatedAt(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CategoryUpdate) SetNotNilTitle(value *string) *CategoryUpdate {
	if value != nil {
		return c.SetTitle(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CategoryUpdateOne) SetNotNilTitle(value *string) *CategoryUpdateOne {
	if value != nil {
		return c.SetTitle(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CategoryCreate) SetNotNilTitle(value *string) *CategoryCreate {
	if value != nil {
		return c.SetTitle(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CategoryUpdate) SetNotNilRemark(value *string) *CategoryUpdate {
	if value != nil {
		return c.SetRemark(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CategoryUpdateOne) SetNotNilRemark(value *string) *CategoryUpdateOne {
	if value != nil {
		return c.SetRemark(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CategoryCreate) SetNotNilRemark(value *string) *CategoryCreate {
	if value != nil {
		return c.SetRemark(*value)
	}
	return c
}
